name: Node CI

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [8.x, 10.x, 12.x]

        steps:
            - uses: actions/checkout@v1
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1

              with:
                  node-version: ${{ matrix.node-version }}
            - name: install, bootstrap and test
              run: |
                  npm run setup:ci
                  npm run test:root
              env:
                  CI: true
            - name: deploy to github pages
              run: |
                  npm run setup:ci
                  npm run build:all
                  npm run docs
                  npm run deploy:docs
              env:
                  CI: true
